name: My first Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:
        - name: CHeckout Repo
          uses: actions/checkout@v4
        
        - name: Echo something out
          run: echo "Bola this is your first Github Action Workflow"
        
        - name: List files
          run: ls
        
        - name: Read the ReadMe file
          run: cat README.md