name: This is my first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps:
        - name: CHeckout Repo
          uses: actions/checkout@v4
        
        - name: Run the below list of commands
          run: | 
            echo "Bola this is your first Github Action Workflow"
            ls
            cat README.md